### ISSUE TITLE
What happened to request_value / synchronous message exchange

### ISSUE THREAD

**Issue by unclevlad** [Stiffstream/sobjectizer#22]
We use so_5 via vcpkg. We were just forced to update and cannot build because request_value is no longer supported. Has the synchronous functionality been removed?

**Comment by eao197** [comment]
Hi!

Since v.5.6.0 this functionality is available in some different form via [so5extra](https://github.com/Stiffstream/so5extra) project: https://github.com/Stiffstream/so5extra/wiki/so5extra-1.4-Synchronous-Interaction
so5extra is also available via vcpkg. It's also available via conan.

Note that so5extra-1.4.0 and more fresh versions of so5extra are distributed under BSD-3-CLASE (same as SObjectizer itself).

**Comment by eao197** [comment]
Please also note that SO-5.6 and 5.7 contain many incompatible changes from SO-5.5 and older versions:

https://github.com/Stiffstream/sobjectizer/wiki/v.5.6.0
https://github.com/Stiffstream/sobjectizer/wiki/v.5.7.0
