### ISSUE TITLE
Get dispatcher by name from an environment

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [Stiffstream/sobjectizer#6]
Hello.

Is it possible to get a dispatcher from an SObjectizer environment with name (like it can be done already with mbox)? Seems like it's not available for now.

Why it can be useful? The same reason as for mboxes - if I want to create an agent on some specific dispatcher and don't want to pass through many layers dispatcher binder.

What do you think about such feature?

Thank you.

**Comment by eao197** [comment]
No, named dispatchers were a part of SObjectizer up to v.5.5 but were deprecated and removed in v.5.6.

It is because in practice they were not as useful as expected.

The main problem is that every dispatcher can have its own unique interface and the binding of an agent to a dispatcher can require different parameters. You can compare an interface of disp_handle of [one_thread](https://github.com/Stiffstream/sobjectizer/blob/master/dev/so_5/disp/one_thread/pub.hpp#L65-L72), [active_group](https://github.com/Stiffstream/sobjectizer/blob/master/dev/so_5/disp/active_group/pub.hpp#L178-L185), or so5extra's [asio_thread_pool](https://github.com/Stiffstream/so5extra/blob/master/dev/so_5_extra/disp/asio_thread_pool/pub.hpp#L286-L292) dispatchers.

This situation is completely different from the case of mboxes where each mbox implements the same interface.

Anyway, if you have a case where you want to have a dictionary of similar dispatchers (or wrap different dispatchers under the same unified interface) you can implement such a dictionary by yourself and attach that dispatcher to SObjectizer's Environment as a [layer](https://github.com/Stiffstream/sobjectizer/blob/master/dev/so_5/so_layer.hpp#L30). Unfortunately, there is no example of custom layers in the standard SObjectizer's examples, but [there are some unit-tests for layres](https://github.com/Stiffstream/sobjectizer/tree/master/dev/test/so_5/layer).

The basic idea is:
```cpp
class disp_binder_dictionary_layer_t : public so_5::layer_t
{
   using map_t = std::map<std::string, so_5::disp_binder_shptr_t, std::less<>>;

   std::mutex m_lock;
   map_t m_dict;

public:
   // There is no need to override start()/shutdown()/wait() methods
   // because the basic implementation does nothing.

   void add(std::string name, so_5::disp_binder_shptr_t binder)
   {
      std::lock_guard l{m_lock};
      auto [it, inserted] = m_dict.emplace(std::move(name), std::move(binder));
      if(!inserted)
         throw std::runtime_error(name + ": is not unique name");
   }

   std::optional<so_5::disp_binder_shptr_t>
   try_get(std::string_view name) noexcept
   {
      std::lock_guard l{m_lock};
      if(const auto it = m_dict.find(name); it != m_dict.end())
         return { it->second };
      else
         return std::nullopt;
   }

   so_5::disp_binder_shptr_t
   get(std::string_view name)
   {
      auto r = try_get(name);
      if(!r) throw std::runtime_error("binder is not found");
      return std::move(*r);
   }
};
...
so_5::launch([](so_5::environment_t & env) {...},
   [](so_5::environment_params_t & params) {
      params.add_layer(std::make_unique<disp_binder_dictionary_layer_t>());
      ...
   });
...
// Somewhere inside your application code:
so_environment().query_layer<disp_binder_dictionary_layer_t>()->add("my_disp", ...);
...
so_environment().introduce_coop(
   so_environment().query_layer<disp_binder_dictionary_layer_t>()->get("my_disp"),
   ...);
```

**Comment by ZaMaZaN4iK** [comment]
Got it. Thank you a lot. Will be fine, if you add an example with SObjectizer layers to the official examples. But for me your answer is enough.

I think I can close it.

**Comment by ZaMaZaN4iK** [comment]
By the way, if anyone else will use in the future the example above, you should fix one thing - use-after-move in `add` method: variable `name` is moved into distionary and then used during exaception message building. Be careful with that (catched with Clang-Tidy btw)
