### ISSUE TITLE
Generic message limits for all message types

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [Stiffstream/sobjectizer#9]
Hello.

I've read about message limits https://github.com/Stiffstream/sobjectizer/wiki/SO-5.7-InDepth-Message-Limits and a post on Habrahabr about [collector-performer](https://habr.com/ru/post/310818/) pattern.

But I am a little bit wondered, that message limits can be defined only for specific messages. Seems like it's not possible (at least in easy way) define message limits for all message types in a mbox.

Is there any way for doing such thing in SObjectizer? For now I see only one option: inherit all message types from some `class generic_message_t` and then define `limit_and_X<generic_message_t>` (I hope it works).

**Comment by eao197** [comment]
> Seems like it's not possible (at least in easy way) define message limits for all message types in a mbox.

Yes, in the current version of SObjectizer message limits should be specified for a particular messages. Moreover, if an agent defines a message limit for just one message it receives it should also define message limits for all other messages it handles. Otherwise, there will be an error during message subscription.

This limitation can be considered a bit strict. But I think it's better to ask a user to specify limits for all messages (even if a limit will be set to MAX_UINT) than to allow to collect too many messages in the queue because a user forgets about some of the messages.

Also, I should correct you: a limit is set per agent, not per mbox. So there could be a mbox "M" and two agents "A" and "B". Agent "A" set a message limit for a message "Msg" and makes a subscription for "Msg" from "M", but agent "B" doesn't define a limit and can also makes the same subscription. Mbox "M" doesn't store the info about message limits. So if "msg" is sent to "M" then the message limit will be applied to "A", but not to "B".

> For now I see only one option: inherit all message types from some class generic_message_t and then define limit_and_X<generic_message_t> (I hope it works).

This approach won't work because message limits and subscriptions are made for a particular message type. If you have a base class "my_message_t" with two derived classes "first_t" and "second_t", and then create a subscription to "my_message_t" then you won't receive messages if they are sent as `send<first_t>(...)` and `send<second_t>(...)`. The same principle with message limits.

**Comment by ZaMaZaN4iK** [comment]
>But I think it's better to ask a user to specify limits for all messages (even if a limit will be set to MAX_UINT)

On the one hand, you are right. On the another hand in my case a have a lot of message types, which shall be processed by one agent type. And that's not very convenient to define manually limits for every message types (since now I shall specify limits manually for every message type). If I want to set limit for any message type - allowing setting a limit for all messages without manual work will be fine, since it fixes a problem with "Ah, forgot again to define here a limit for new message and got again runtime error-notification about that". 

We can discuss more about usefullness of such feature. FMPOV, it's fine to have such mechanism in SObjectizer, but I cannot guess how difficult if implementation of such feature, performance costs, etc (since I am not a SObjectizer dev :)

>Also, I should correct you: a limit is set per agent, not per mbox.

Yeah, sorry. You are completely right.

>This approach won't work because message limits and subscriptions are made for a particular message type.

Got it. Thank you.

Hmm... Seems like if I want to set a limit for any message types, message chain is the only built-in approach, right? Unfortunately, message chain doesn't support subscription mechanism (for now I am trying to emulate it with `receive` and corresponding handlers for message types).

**Comment by eao197** [comment]
I had an idea about something like `default_message_limit` in the past, but it wasn't implemented because message limits are rarely used and nobody asked for such a feature. Maybe it's time to return to that idea. But I'm afraid there won't be free time for it on this week :(

> Seems like if I want to set a limit for any message types, message chain is the only built-in approach, right?

Yes. But mchains allow setting a limit for the total amount of messages regardless of their types. So if you create a mchain with capacity 100 there could be 50 messages of type M1 and 50 messages of type M2. Or 100 messages of type M1, but none of type M2.

> message chain doesn't support subscription mechanism

This is a feature I didn't find a way to implement yet. It will be cool to have an ability to subscribe an agent to a mchain and deliver messages from mchain to the usual event handlers of the subscribed agent.

**Comment by ZaMaZaN4iK** [comment]
>But I'm afraid there won't be free time for it on this week

No problem :) Since there is another way for doing the same thing - it's fine for now. 

If you are really not against of such feature - I suggest don't close the issue :) Maybe someday it will be implemented and then you can link PR with required functionality with this issue, so I (and other interested in the feature watchers) will get a notification.

Thank you for the answers.

**Comment by eao197** [comment]
There you can see how the draft version of "generic message limits" looks like:
https://github.com/Stiffstream/sobjectizer/blob/a48c11066211c72fb37a7584b2a945086638477e/dev/sample/so_5/default_message_limits/main.cpp#L158-L163

**Comment by eao197** [comment]
Implemented in v.5.7.1.

More info can be found in the Wiki: https://github.com/Stiffstream/sobjectizer/wiki/v.5.7.1 and https://github.com/Stiffstream/sobjectizer/wiki/SO-5.7-InDepth-Message-Limits
